In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [25]:
import numpy as np

In [3]:
str_arr = np.array(['Jane','Rose','Kevin'])
str_arr

array(['Jane', 'Rose', 'Kevin'], dtype='<U5')

In [5]:
numpy_ndaarr = np.array([[1,2,3],[4,5,6]])
numpy_ndaarr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
list_of_integers = [0,1,2,3]


In [7]:
arr1 = np.array(list_of_integers)

In [8]:
arr1

array([0, 1, 2, 3])

In [9]:
arr1 + 3

array([3, 4, 5, 6])

In [10]:
length = np.array([10,12,20,5])
width = np.array([13,15,16,4])
area = length*width
print(area)

[130 180 320  20]


In [16]:
A = 25.sqrt()

SyntaxError: invalid decimal literal (3871986708.py, line 1)

In [18]:
print(25.sqrt(25))

SyntaxError: invalid decimal literal (1882301183.py, line 1)

In [19]:
numsqrt(25)

NameError: name 'numsqrt' is not defined

In [20]:
import math

In [22]:
print(int(math.sqrt(25)))

5


In [23]:
arr2 = np.array([9,16,25,49])

In [32]:
np.sqrt(arr2)

array([3., 4., 5., 7.])

In [33]:
cuberoot = np.power(arr2, 1/3)

In [34]:
cuberoot

array([2.08008382, 2.5198421 , 2.92401774, 3.65930571])

In [37]:
cuberooot.ceil()

NameError: name 'cuberooot' is not defined

In [38]:
print(math.ceil(cuberoot))

TypeError: only length-1 arrays can be converted to Python scalars

In [45]:
cuberoot = np.power(int(arr2), 1/3)

TypeError: only length-1 arrays can be converted to Python scalars

In [40]:
cuberoot

array([2.08008382, 2.5198421 , 2.92401774, 3.65930571])

In [46]:
arr2

array([ 9, 16, 25, 49])

In [ ]:
arr3 = np.array([1,2,3